spring:
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'Asia/Shanghai'
    # JsonInclude.Include
    default-property-inclusion: NON_NULL

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://nacos.openwes.com:3306/scada?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 100
      auto-commit: true
      pool-name: ${spring.application.name}_datasource_pool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 100000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: null
          subscriptionsPerConnection: 5
          clientName: null
          address: redis://nacos.openwes.com:6379
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 32
          connectionPoolSize: 64
          database: 3
          dnsMonitoringInterval: 5000
        threads: 0
        nettyThreads: 0
        codec:
          class: "org.redisson.codec.JsonJacksonCodec"
        transportMode: "NIO"
        lockWatchdogTimeout: 10000
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 9010
  max-http-request-header-size: 1024000

bean-searcher:
  params:
    pagination:
      maxAllowedSize: 100000
      start: 1
      size: perPage

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - env
          - scheduledtasks

  endpoint:
    health:
      show-details: always

logging:
  config: classpath:logback-spring.xml
  logback:
    rollingpolicy:
      max-file-size: 100MB    # Max size of a single log file
      max-history: 10        # Max days to keep archived logs
      total-size-cap: 50GB
  level:
    cn.zhxu.bs: DEBUG
