version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ./client
      args:
        NPM_REGISTRY: ${NPM_REGISTRY:-https://registry.npmjs.org}
    ports:
      - "80:80"
    networks:
      - my-network

  # Gateway Server
  gateway-server:
    build:
      context: ./server/
      target: gateway
    ports:
      - "8090:8090"
    depends_on:
      - mysql
      - redis
    networks:
      - my-network

  # scada Server
  scada-server:
    build:
      context: ./server/
      target: scada
    ports:
      - "9010:9010"
    depends_on:
      - mysql
      - redis
    networks:
      - my-network

  # MySQL Service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql_data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d  # Mount SQL file for initialization
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      my-network:
        aliases:
          - nacos.openwes.com

  # Redis Service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      my-network:
        aliases:
          - nacos.openwes.com

# Networks
networks:
  my-network:
    driver: bridge
