-- ============================================================
-- SCADA Menu Initialization
-- system_code: 'scada'
-- ID range: 1200000000+
-- ============================================================

-- ---- type=1: System Root ----
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1200000000, 'admin', 'scada', 0, 1, 'SCADA', NULL, 'scada', 3, 'scadaapp', '', 1, 0, 0, '', NULL);

-- ---- type=2: Groups (parent = 1200000000) ----
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201000000, 'admin', 'scada', 1200000000, 2, 'SCADA监控', NULL, '/scada/monitor', 1, NULL, '/scada/monitor', 1, 0, 0, '', 0);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1202000000, 'admin', 'scada', 1200000000, 2, 'SCADA日志', NULL, '/scada/log', 2, NULL, '/scada/log', 1, 0, 0, '', 0);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1203000000, 'admin', 'scada', 1200000000, 2, 'SCADA统计', NULL, '/scada/statics', 3, NULL, '/scada/statics', 1, 0, 0, '', 0);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1204000000, 'admin', 'scada', 1200000000, 2, '设备维护', NULL, '/scada/maintenance', 4, NULL, '/scada/maintenance', 1, 0, 0, '', 0);

-- ---- type=2: Pages under SCADA监控 (parent = 1201000000) ----
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201010000, 'admin', 'scada', 1201000000, 2, '实时监控', NULL, '/scada/monitor/equipment-scada', 1, NULL, '/scada/monitor/equipment-scada', 1, 0, 0, '', 0);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201020000, 'admin', 'scada', 1201000000, 2, '设备监控', NULL, '/scada/monitor/equipment-monitor', 2, NULL, '/scada/monitor/equipment-monitor', 1, 0, 0, '', 0);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201030000, 'admin', 'scada', 1201000000, 2, '报警历史', NULL, '/scada/monitor/alarm-history', 3, NULL, '/scada/monitor/alarm-history', 1, 0, 0, '', 0);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201040000, 'admin', 'scada', 1201000000, 2, '颜色配置', NULL, '/scada/monitor/color-config', 4, NULL, '/scada/monitor/color-config', 1, 0, 0, '', 0);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201050000, 'admin', 'scada', 1201000000, 2, '电表管理', NULL, '/scada/monitor/meter-management', 5, NULL, '/scada/monitor/meter-management', 1, 0, 0, '', 0);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201060000, 'admin', 'scada', 1201000000, 2, '网络拓扑图', NULL, '/scada/monitor/network-topology', 6, NULL, '/scada/monitor/network-topology', 1, 0, 0, '', 0);

-- ---- type=2: Pages under SCADA日志 (parent = 1202000000) ----
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1202010000, 'admin', 'scada', 1202000000, 2, 'SCADA日志', NULL, '/scada/log/scada-log', 1, NULL, '/scada/log/scada-log', 1, 0, 0, '', 0);

-- ---- type=2: Pages under SCADA统计 (parent = 1203000000) ----
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1203010000, 'admin', 'scada', 1203000000, 2, 'SCADA扫描频率', NULL, '/scada/monitor/scada-scan-rate', 1, NULL, '/scada/monitor/scada-scan-rate', 1, 0, 0, '', 0);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1203020000, 'admin', 'scada', 1203000000, 2, 'SCADA流量统计', NULL, '/scada/monitor/scada-traffic-statistics', 2, NULL, '/scada/monitor/scada-traffic-statistics', 1, 0, 0, '', 0);

-- ---- type=2: Pages under 设备维护 (parent = 1204000000) ----
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1204010000, 'admin', 'scada', 1204000000, 2, '设备巡检', NULL, '/scada/maintenance/equipment-inspection', 1, NULL, '/scada/maintenance/equipment-inspection', 1, 0, 0, '', 0);

-- ---- type=3: Button permissions under 设备监控 (parent = 1201020000) ----
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201020001, 'admin', 'scada', 1201020000, 3, '新增/修改', NULL, 'post:/scada/device-monitor/createOrUpdate', 1, NULL, NULL, 1, 0, 0, '', NULL);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201020002, 'admin', 'scada', 1201020000, 3, '删除', NULL, 'post:/scada/device-monitor/delete/${id}', 2, NULL, NULL, 1, 0, 0, '', NULL);

-- ---- type=3: Button permissions under 颜色配置 (parent = 1201040000) ----
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201040001, 'admin', 'scada', 1201040000, 3, '新增/修改', NULL, 'post:/scada/color-config/createOrUpdate', 1, NULL, NULL, 1, 0, 0, '', NULL);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201040002, 'admin', 'scada', 1201040000, 3, '删除', NULL, 'post:/scada/color-config/delete/${id}', 2, NULL, NULL, 1, 0, 0, '', NULL);

-- ---- type=3: Button permissions under 电表管理 (parent = 1201050000) ----
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201050001, 'admin', 'scada', 1201050000, 3, '新增/修改', NULL, 'post:/scada/meter/createOrUpdate', 1, NULL, NULL, 1, 0, 0, '', NULL);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201050002, 'admin', 'scada', 1201050000, 3, '删除', NULL, 'post:/scada/meter/delete/${id}', 2, NULL, NULL, 1, 0, 0, '', NULL);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201050003, 'admin', 'scada', 1201050000, 3, '查看用电数据', NULL, 'post:/scada/meter/powerData', 3, NULL, NULL, 1, 0, 0, '', NULL);

-- ---- type=3: Button permissions under 网络拓扑图 (parent = 1201060000) ----
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201060001, 'admin', 'scada', 1201060000, 3, '新增/修改', NULL, 'post:/scada/network-device/createOrUpdate', 1, NULL, NULL, 1, 0, 0, '', NULL);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201060002, 'admin', 'scada', 1201060000, 3, '删除', NULL, 'post:/scada/network-device/delete/${id}', 2, NULL, NULL, 1, 0, 0, '', NULL);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1201060003, 'admin', 'scada', 1201060000, 3, '查看拓扑', NULL, 'get:/scada/network-device/topology', 3, NULL, NULL, 1, 0, 0, '', NULL);

-- ---- type=3: Button permissions under 设备巡检 (parent = 1204010000) ----
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1204010001, 'admin', 'scada', 1204010000, 3, '新增/修改巡检计划', NULL, 'post:/scada/inspection-plan/createOrUpdate', 1, NULL, NULL, 1, 0, 0, '', NULL);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1204010002, 'admin', 'scada', 1204010000, 3, '删除巡检计划', NULL, 'post:/scada/inspection-plan/delete/${id}', 2, NULL, NULL, 1, 0, 0, '', NULL);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1204010003, 'admin', 'scada', 1204010000, 3, '查看日历', NULL, 'get:/scada/inspection-plan/calendar', 3, NULL, NULL, 1, 0, 0, '', NULL);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1204010004, 'admin', 'scada', 1204010000, 3, '导入', NULL, 'post:/scada/inspection-plan/import', 4, NULL, NULL, 1, 0, 0, '', NULL);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1204010005, 'admin', 'scada', 1204010000, 3, '新增/修改巡检记录', NULL, 'post:/scada/inspection-record/createOrUpdate', 5, NULL, NULL, 1, 0, 0, '', NULL);
INSERT INTO `u_menu` (`id`, `create_user`, `system_code`, `parent_id`, `type`, `title`, `description`, `permissions`, `order_num`, `icon`, `path`, `enable`, `create_time`, `update_time`, `update_user`, `iframe_show`) VALUES (1204010006, 'admin', 'scada', 1204010000, 3, '删除巡检记录', NULL, 'post:/scada/inspection-record/delete/${id}', 6, NULL, NULL, 1, 0, 0, '', NULL);
