rootProject.name = 'SCADA'

include 'modules-user:user'
include 'modules-user:user-api'

include 'modules-scada:scada-core'
include 'modules-scada:scada-api'

include 'modules-gateway:gateway-core'

include 'modules-api-platform:api-platform'
include 'modules-api-platform:api-platform-api'

include 'modules-search:search-core'
include 'modules-search:search-api'

include 'modules-utils:common-utils'
include 'modules-utils:domain-event'
include 'modules-utils:distribute-lock'
include 'modules-utils:mq'
include 'modules-utils:distribute-file'
include 'modules-utils:exception-handler'
include 'modules-utils:common-import'
include 'modules-utils:distribute-scheduler'

include 'server:gateway-server'
include 'server:scada-server'

