dependencies {

    implementation project(path: ":modules-utils:exception-handler", configuration: 'default')
    implementation project(path: ":modules-utils:common-utils", configuration: 'default')

    implementation project(path: ":modules-api-platform:api-platform", configuration: 'default')
    implementation project(path: ":modules-search:search-core", configuration: 'default')
    implementation project(path: ":modules-user:user", configuration: 'default')
    implementation project(path: ":modules-scada:scada-core", configuration: 'default')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.cloud:spring-cloud-starter-bootstrap'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui'

    implementation 'org.apache.skywalking:apm-toolkit-logback-1.x'

    implementation 'mysql:mysql-connector-java'

    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    implementation 'org.liquibase:liquibase-core'

}

test {
    useJUnitPlatform()
}
